apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: aws-encryption-provider
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aws-encryption-provider
    app.kubernetes.io/part-of: mce-24
  name: aws-encryption-provider
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: aws-encryption-provider
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: aws-encryption-provider
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/red-hat-acm-tenant/mce-24/aws-encryption-provider@sha256:bc50d9d21fd1f7ea1617137abde0c67955c326d3ad9c5bcc7f6d2298b85ccbfd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
