apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: helloprow-go-wcoc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: helloprow-go-wcoc
    app.kubernetes.io/part-of: mce-24
  name: helloprow-go-wcoc
  namespace: red-hat-acm-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: helloprow-go-wcoc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: helloprow-go-wcoc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/red-hat-acm-tenant/mce-24/helloprow-go-wcoc@sha256:ae3c859b3ece5b42b41b8da75590e7f4afb99f6f2d92eef95b03c00a39eca19a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 4321
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
