apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: discovery-hvbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discovery-hvbe
    app.kubernetes.io/part-of: mce-24
  name: discovery-hvbe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: discovery-hvbe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: discovery-hvbe
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
