apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: helloprow-go-wcoc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/red-hat-acm-tenant/mce-24/helloprow-go-wcoc@sha256:578e8a05fd39dcb2052edb391bb2d69a5b2812409972e98a08f36b206c50920c
        name: container-image
        resources: {}
status: {}
